project:
  type: website
  output-dir: docs
  resources:
    - cv.pdf

website:
  title: "Laura Pacin"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Event organization"
        href: eventorganization/index.qmd
      - text: "CV"
        href: cv.pdf
    right:
      - icon: linkedin
        href: https://linkedin.com/in/laurapacin
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:laurapacin@gmail.com
        aria-label: Email

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <meta name="google-site-verification" content="UAUSraGjHYn4iCnyp-xNrh839ZFrGyzOixv7p98UPqQ" />
